#项目访问端口号
server:
  port: 8080
  servlet:  #项目访问的根路径
    context-path: /community

# 关闭thymeleaf的缓存
spring:
  thymeleaf:
    cache: false

#  kafka
  kafka:
    bootstrap-servers: 101.43.133.25:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

#  rabbitmq:
#    host: 81.69.27.163
#    port: 5672
#    username: guest
#    password: guest


  #配置邮箱，该邮箱用于当作系统的服务端邮箱，帮我们实现邮箱的转发功能
  # MailProperties
  mail:
    host: smtp.sina.com
    port: 465
    username: lms0121@sina.com
    password: 9ddf4b40d7d10d59
    # 目的就是保证发送邮件的安全性得到保障
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  # es
#
#  data:
#    elasticsearch:
##      cluster-name: my-application
##      #节点的地址，注意api模式下端口号是9300，千万不要写成9200
##      #是否开启本地存储
##      repositories:
##        enabled: false
#      client:
#        reactive:
#          endpoints: 101.43.133.25:9300

  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.133.25:3306/nk?serverTimezone=GMT%2B8
    username: root
    password: 123456

# 配置redis
  redis:
    # Redis数据库索引（默认为0）
    database: 11
    # Redis服务器地址（）
    host: 101.43.133.25
    # Redis服务器连接端口
    port: 6379

# mybatis相关
mybatis:
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mappers/*.xml
  #标注实体类位置
  type-aliases-package: com.liu.nkcommunity.domain
  configuration:
    map-underscore-to-camel-case: true
    # 插入数据之后，会自动的将生成的id回填到用户的id属性中
    use-generated-keys: true


# 打印日记信息
logging:
  level:
    com.liu.nkcommunity.mapper: DEBUG

#社区域名
community:
  path:
    domain: http://localhost:8080
    upload: D:/nkFile
