#项目访问端口号
server:
  port: 8080
  servlet:  #项目访问的根路径
    context-path: /community

# 关闭thymeleaf的缓存
spring:
  thymeleaf:
    cache: false

# 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nk?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456

# mybatis相关
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.liu.nkcommunity.domain

# 打印日记信息
logging:
  level:
    com.liu.nkcommunity.mapper: DEBUG




